"use client";

import { Suspense, useEffect, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { loadValidatedProject } from "@/lib/load-project";
import { activeScenario } from "@/store/editor";
import { buildReportSnapshot, type CalculationSettings } from "@/lib/report-snapshot";
import { renderReportHtml } from "@/lib/report-view";

/**
 * Read-only report view. Builds an immutable report snapshot from the stored
 * project and renders the print-friendly report. Query flags emulate share-link
 * options (hidePrices/hideCustomerFields/print) so a future server route can
 * pass the same options after validating a share token.
 *
 * `useSearchParams` MUST be used inside a <Suspense> boundary (Next 14 App
 * Router). The inner component that reads it is wrapped below. Snapshot building
 * is guarded so malformed/missing data yields a localized error, not a crash.
 */
const CALC: CalculationSettings = {
  gridResolutionM: 0.5,
  bands: ["2.4", "5", "6"],
  environment: "office",
  noiseFloorDbm: { "2.4": -95, "5": -92, "6": -92 },
  efficiencyFactor: 0.5,
};

export default function ReportPage() {
  return (
    <Suspense
      fallback={
        <div className="flex h-screen items-center justify-center text-base-muted">
          Preparing report…
        </div>
      }
    >
      <ReportInner />
    </Suspense>
  );
}

function ReportInner() {
  const { id } = useParams<{ id: string }>();
  const params = useSearchParams();
  const [html, setHtml] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const loaded = await loadValidatedProject(id);
        if (!loaded.ok) {
          if (!cancelled) {
            setError(
              loaded.reason === "not-found"
                ? "Report not found. The project may have been deleted."
                : "This report could not be generated: the stored project data is invalid or from an unsupported version.",
            );
          }
          return;
        }
        const project = loaded.project;
        const scn = activeScenario(project);
        const snapshot = buildReportSnapshot(project, scn, {}, CALC, {
          now: new Date().toISOString(),
        });
        const out = renderReportHtml(snapshot, {
          hidePrices: params.get("hidePrices") === "1",
          hideCustomerFields: params.get("hideCustomer") === "1",
          print: params.get("print") === "1",
        });
        if (!cancelled) setHtml(out);
      } catch (err) {
        // Localized, user-readable error — never an unhandled client exception.
        if (!cancelled) {
          setError(
            "This report could not be generated from the current project data. The project may be incomplete or use an unsupported format.",
          );
          // Structured, sensitive-data-free client log.
          console.error("[report] snapshot build failed", {
            route: "/report/[id]",
            message: err instanceof Error ? err.message : String(err),
          });
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id, params]);

  if (error) {
    return (
      <div className="flex h-screen flex-col items-center justify-center gap-3 px-6 text-center text-base-muted">
        <p className="max-w-md">{error}</p>
        <a href="/" className="btn">
          Back to projects
        </a>
      </div>
    );
  }
  if (!html) {
    return (
      <div className="flex h-screen items-center justify-center text-base-muted">
        Preparing report…
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#f4f5f7]">
      <div className="sticky top-0 z-10 flex items-center justify-between border-b border-base-border bg-base-panel px-4 py-2 text-sm print:hidden">
        <span className="font-medium">Design report (read-only)</span>
        <button className="btn btn-primary !py-1" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
      </div>
      {/* The report HTML is generated by our own renderer from a snapshot. */}
      <iframe
        title="Design report"
        className="h-[calc(100vh-44px)] w-full border-0"
        srcDoc={html}
      />
    </div>
  );
}
