"use client";

import { useEffect, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { localProjectStore } from "@/lib/storage";
import { activeScenario } from "@/store/editor";
import { buildReportSnapshot, type CalculationSettings } from "@/lib/report-snapshot";
import { renderReportHtml } from "@/lib/report-view";

/**
 * Read-only report view. Builds an immutable report snapshot from the stored
 * project and renders the print-friendly report. Query flags emulate share-link
 * options (hidePrices/hideCustomerFields/print) so a future server route can
 * pass the same options after validating a share token.
 *
 * NOTE (documented): in the client-persisted MVP this reads the local project.
 * A production build would render from a stored snapshot fetched after
 * server-side share-token validation (see src/lib/share-link.ts).
 */
const CALC: CalculationSettings = {
  gridResolutionM: 0.5,
  bands: ["2.4", "5", "6"],
  environment: "office",
  noiseFloorDbm: { "2.4": -95, "5": -92, "6": -92 },
  efficiencyFactor: 0.5,
};

export default function ReportPage() {
  const { id } = useParams<{ id: string }>();
  const params = useSearchParams();
  const [html, setHtml] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      const project = await localProjectStore.get(id);
      if (!project) {
        setError("Report not found.");
        return;
      }
      const scn = activeScenario(project);
      const snapshot = buildReportSnapshot(project, scn, {}, CALC, {
        now: new Date().toISOString(),
      });
      setHtml(
        renderReportHtml(snapshot, {
          hidePrices: params.get("hidePrices") === "1",
          hideCustomerFields: params.get("hideCustomer") === "1",
          print: params.get("print") === "1",
        }),
      );
    })();
  }, [id, params]);

  if (error) {
    return <div className="flex h-screen items-center justify-center text-base-muted">{error}</div>;
  }
  if (!html) {
    return (
      <div className="flex h-screen items-center justify-center text-base-muted">
        Preparing report…
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#f4f5f7]">
      <div className="sticky top-0 z-10 flex items-center justify-between border-b border-base-border bg-base-panel px-4 py-2 text-sm print:hidden">
        <span className="font-medium">Design report (read-only)</span>
        <button className="btn btn-primary !py-1" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
      </div>
      {/* The report HTML is generated by our own renderer from a snapshot. */}
      <iframe
        title="Design report"
        className="h-[calc(100vh-44px)] w-full border-0"
        srcDoc={html}
      />
    </div>
  );
}
